### ISSUE TITLE
Remark: Memory demand (min. 8 GB it seems)

### ISSUE THREAD

**Issue by cweickhmann** [OpenSlides/openslides-docker-compose#1]
Hi! This is less of an issue and rather a remark.

I've been doing some guesswork lately as OpenSlides 3.0 would build at all on a VM, crashing with a rather weird `npm` related error that I could not reproduce on my machine at home.

As it turns out, it seems that 4 GB of RAM simply is not enough for the build process (`server/build.sh`) when it goes through `npm run build` (I think) in the `Dockerfile`.

With 8 GB, however, it worked flawlessly.

Just wanted to leave this here for other lost souls ^^

**Comment by moschlar** [comment]
I had this problem with 2 GB, but 4 GB worked for me.

**Comment by tsiegleauq** [comment]
That's due to the angular client. Building the client in production mode requires (at least) 4GB of Memory

https://github.com/OpenSlides/OpenSlides/blob/master/client/package.json#L13

**Comment by cweickhmann** [comment]
I see. I suspected that.
Wouldn't it make sense to throw a warning when less is available?
Or note it somewhere in the docs?

**Comment by cweickhmann** [comment]
We'll I ran into this issue twice, though in edge cases:
* Building on a RaspberryPi (nice and mobile for events with only a few clients)
* Building on a rented cloud node where I initially selected only 4GB RAM because that's usually enough.

I would've appreciated a note. Mostly because the error thrown was rather cryptic and not pointing directly to a lack of RAM.

12 Mar 2020 19:11:16 Sean <notifications@github.com>:

**Comment by gsiv** [comment]
Thank you for your comments.  I have added the requirement to the README file (c.f. fe895e06924a53bb532dfd6d91f2faf7b9b72958).

**Comment by tsiegleauq** [comment]
@gsiv the client now requires less RAM to for a prod-build since the angular9 update.

**Comment by cweickhmann** [comment]
Thanks for the info! :-)
