### ISSUE TITLE
Incompatible Note.js 

### ISSUE THREAD

**Issue by code-sport** [OpenSlides/openslides-docker-compose#3]
During executing from `./server/build.sh` I got following error:

> Node.js version undefined detected.
> The Angular CLI requires a minimum Node.js version of either v10.13 or v12.0.
> 
> Please update your Node.js version or visit https://nodejs.org/ for additional instructions.
> The command '/bin/sh -c ng config -g cli.warnings.versionMismatch false &&   cd client &&   npm install' returned a non-zero code: 3

How can the the Node.js specified which are used?

**Comment by forkedjensh** [comment]
I am having the same issue by running `./server/build.sh` in step 33/38 but with a defined Node.js vesion:
```
Node.js version v11.15.0 detected.
The Angular CLI requires a minimum Node.js version of either v10.13 or v12.0.

Please update your Node.js version or visit https://nodejs.org/ for additional instructions.
The command '/bin/sh -c ng config -g cli.warnings.versionMismatch false &&   cd client &&   npm install' returned a non-zero code: 3
```

**Comment by forkedjensh** [comment]
I do not get the build working with Node.js v10 or v12 (versions can be adjusted in `server/node-apt/nodesource.list`). The build process gets killed:

```
> OpenSlides3-Client@3.1.1 ng-high-memory /build/app/client
> node --max_old_space_size=4096 ./node_modules/@angular/cli/bin/ng "build" "--prod"

Killed
```

**Comment by forkedjensh** [comment]
#4 addresses this and allows the image build.

**Comment by gsiv** [comment]
Instead of updating Node, we chose to pin the Angular version, cf. 315f3786a3047df491613bcea8051deeed2e3cb4.  Please test if this works for you.

**Comment by forkedjensh** [comment]
@gsiv Thanks, that works. I will close the pull request.
