### ISSUE TITLE
./server/build.sh failes at Step 34

### ISSUE THREAD

**Issue by johannesWeigel** [OpenSlides/openslides-docker-compose#5]
While pre-building the server it failes at step 34 - I'm a little bit lost with this error-logging
![image](https://user-images.githubusercontent.com/35703902/76288399-eb4ce600-62a6-11ea-8ff8-55fb328556fd.png)

I updated my local npm- and python3-version but it still seems to fail in line 88 of the server/Dockerfile `npm run build && \`.

Is the mistake on my side or doesnt it work with some specific machines/evironments?

**Comment by gsiv** [comment]
> Is the mistake on my side or doesnt it work with some specific machines/evironments?

My guess is that you are seeing the issue reported in https://github.com/OpenSlides/openslides-docker-compose/issues/1.  So, make sure that you have enough RAM for the build process.
