### ISSUE TITLE
Postfix connection refused on port 25

### ISSUE THREAD

**Issue by jwinzer** [OpenSlides/openslides-docker-compose#9]
I get a connection refused error when trying to send mail:

Sep 22 08:57:19 dev postfix/postfix-script[110]: starting the Postfix mail system
Sep 22 08:57:19 dev postfix/master[1]: daemon started -- version 3.4.14, configuration /etc/postfix
Sep 22 09:05:15 dev postfix/smtpd[114]: connect from devdemo3voteathomede_server_1.devdemo3voteathomede_back[172.22.0.9]
Sep 22 09:05:15 dev postfix/smtpd[114]: 948A2120DA0: client=devdemo3voteathomede_server_1.devdemo3voteathomede_back[172.22.0.9]
Sep 22 09:05:15 dev postfix/cleanup[119]: 948A2120DA0: message-id=<160076551559.40.2821107839314838901@737f4f56c332>
Sep 22 09:05:15 dev postfix/qmgr[112]: 948A2120DA0: from=<noreply@dev.demo3.votehome.de>, size=763, nrcpt=1 (queue active)
Sep 22 09:05:15 dev postfix/smtpd[114]: disconnect from devdemo3voteathomede_server_1.devdemo3voteathomede_back[172.22.0.9] ehlo=1 mail=1 rcpt=1 data=1 quit=1 commands=5
Sep 22 09:05:15 dev postfix/smtp[120]: connect to 172.22.0.1[172.22.0.1]:25: Connection refused
Sep 22 09:05:15 dev postfix/smtp[120]: 948A2120DA0: to=<jw@winzer-sw.de>, relay=none, delay=0.02, delays=0.01/0.01/0/0, dsn=4.4.1, status=deferred (connect to 172.22.0.1[172.22.0.1]:25: Connection refused)

My .env is:
DEFAULT_FROM_EMAIL=noreply@dev.demo3.votehome.de
POSTFIX_MYHOSTNAME=dev.demo3.voteathome.de
POSTFIX_RELAYHOST=

Is this a bug or setup issue? Any help is appreciated.

**Comment by gsiv** [comment]
Since you did not configure `POSTFIX_RELAYHOST`, OpenSlides' Postfix service attempts to connect to the Docker host system for use as a relay.  In your case, the host system appears to be rejecting connections, however.

If you intend to use the host system's mail server, make sure it is configured to relay mail from Docker networks.  Otherwise, you may configure any other relaying mail server in `POSTFIX_RELAYHOST` that will accept mail from the system.

**Comment by jwinzer** [comment]
Okay, thanks. Does that mean I have to install postfix in the host system?
Alternatively, can I configure the system to not use a relay, i.e. send mail thru the dockerized postfix?

**Comment by gsiv** [comment]
> Does that mean I have to install postfix in the host system?

Installing Postfix or any other mail server on the host system would be one way of doing it, yes.  A mail server is probably already installed and just needs to be configured for Docker's IP ranges.

> Alternatively, can I configure the system to not use a relay, i.e. send mail thru the dockerized postfix?

The provided Postfix service can not be configured this way.  You can, however, replace it with another Postfix image.  The original setup of this repository (ecef5f30efafbaf72a36bd50a941a745e004156e) used [catatnight/postfix](https://github.com/catatnight/docker-postfix), for example.

Be aware that improperly configured mail servers run the risk of getting rejected, especially by large providers.  The ideal setup, in my opinion, is one where mail is relayed by an established mail server.

**Comment by jwinzer** [comment]
Now I understand. Thanks!
